apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: {app: loadgen}
  template:
    metadata:
      labels: {app: loadgen}
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-pull
      containers:
        - name: loadgen
          image: ghcr.io/nelsudev/zeedfai-loadgen:0.1.0
          env:
            - name: KAFKA_BROKERS
              value: zeedfai-kafka-bootstrap.kafka:9092
            - name: KAFKA_TOPIC
              value: transactions
            - name: BASE_RATE
              value: "100"
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen
  namespace: default
spec:
  selector: {app: loadgen}
  ports:
    - port: 8081
